= Tipps & Tricks
:icons: font
:toc: macro

== Ziele
* Praktische macOS-Funktionen entdecken
* Individuelle Einstellungen kennenlernen

== Aufgaben
. Testen Sie mindestens drei neue Tastenkombinationen oder Kurzbefehle.
. Passen Sie das Dock und die Systemeinstellungen an.

== Tipps & Tricks

=== AI nutzen
Nutzen Sie link:https://chatgpt.com/?openaicom_referred=true[ChatGPT,window=_blank] oder andere KI-Tools aus, um ihre Produktivität zu steigern. Probieren Sie z.B. folgenden Prompt aus:

[source,console]
----
Welches sind die wichtigsten Tastenkürzel für ein effizientes Arbeiten mit macOS?
----

=== Nützliche Youtube-Videos
- *Schreibtisch/Desktop* +
YouTube-Video link:https://www.youtube.com/watch?v=plyPws6H2vI["Hör auf Fenster zu minimieren und mach DAS",window=_blank]
- *Kontrollzentrum* +
 YouTube-Video link:https://www.youtube.com/watch?v=FnDEdBmC5Lw["Du hast GENIALSTE Funktion in macOS Tahoe übersehen!",window=_blank]
- *Option-Taste* +
 YouTube-Video link:https://www.youtube.com/watch?v=mcrwftiISvg["macOS ist GENIAL, wenn du diese Taste kennst!",window=_blank]



== Reflexion
* Welche Funktion haben Sie überrascht oder begeistert?
* Was möchten Sie noch weiter erkunden?
